openapi: 3.0.0
info:
  title: REST reference implementation
  description: This is the reference implementation of a REST API following the G-Cloud
    style guide.
  version: v1
servers:
  - url: /demo/v1
tags:
  - name: ReferenceData
  - name: Organization
  - name: Employer
  - name: Logos
  - name: Documentation
  - name: Monitoring
paths:
  /refData/employerClasses:
    get:
      tags:
        - ReferenceData
      summary: Get the complete reference data list of employer classes
      operationId: getEmployerClasses
      parameters:
        - name: Accept-Language
          in: header
          description: User language
          required: false
          style: simple
          explode: false
          schema:
            type: string
            enum:
              - nl
              - fr
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployerClasses'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /refData/employerClasses/{employerClass}:
    get:
      tags:
        - ReferenceData
      summary: Get the details of a specific employer class
      operationId: getEmployerClass
      parameters:
        - name: employerClass
          in: path
          description: the value of the employer class
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployerClass'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /refData/economicalActivities:
    get:
      tags:
        - ReferenceData
      summary: Get the complete reference data list of economical activities
      operationId: getEconomicalActivities
      parameters:
        - name: lang
          in: query
          schema:
            type: string
            enum:
              - fr
              - nl
              - de
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EconomicalActivities'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /refData/economicalActivities/{economicalActivity}:
    get:
      tags:
        - ReferenceData
      summary: Get the details of a specific economical activity
      operationId: getEconomicalActivity
      parameters:
        - name: economicalActivity
          in: path
          description: the value of the economical activity
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: lang
          in: query
          schema:
            type: string
            enum:
              - fr
              - nl
              - de
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EconomicalActivityDescription'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /organizations:
    get:
      tags:
        - Organization
      summary: List all organizations
      operationId: findOrganizations
      parameters:
        - name: page
          in: query
          description: "Index of the current page, default 1"
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 1
        - name: pageSize
          in: query
          description: "Maximum number of items per page, default 5"
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            default: 5
        - name: name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: startDate_gt
          in: query
          description: Greater than date filter
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organizations'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - Organization
      summary: Create a new organization
      operationId: createOrganization
      requestBody:
        description: Organization data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: location of the created organization
              style: simple
              explode: false
              schema:
                type: string
                format: uri
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      x-content-type: application/json
  /organizations/{enterpriseNumber}:
    get:
      tags:
        - Organization
      summary: Get an organization by its enterprise number
      operationId: getOrganization
      parameters:
        - name: enterpriseNumber
          in: path
          description: Enterprise Number
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/EnterpriseNumber'
      responses:
        "200":
          description: Details of an organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    put:
      tags:
        - Organization
      summary: Update an organization
      operationId: updateOrganization
      parameters:
        - name: enterpriseNumber
          in: path
          description: enterprise number of the organization
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/EnterpriseNumber'
      requestBody:
        description: Data of organization
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      x-content-type: application/json
    delete:
      tags:
        - Organization
      summary: Delete an organization by its enterprisenumber
      operationId: deleteOrganization
      parameters:
        - name: enterpriseNumber
          in: path
          description: Enterprise Number
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/EnterpriseNumber'
      responses:
        "204":
          description: OK
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    patch:
      tags:
        - Organization
      summary: Partially update a organization using JSON Merge Patch. See https://tools.ietf.org/html/rfc7396.
      operationId: patchOrganization
      parameters:
        - name: enterpriseNumber
          in: path
          description: enterprise number of the organization
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/EnterpriseNumber'
      requestBody:
        description: MergePatch of 'schemas/organization.yaml#/components/schemas/Organization'
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/MergePatch'
        required: true
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      x-content-type: application/merge-patch+json
  /logos:
    get:
      tags:
        - Logos
      description: See list of image metadata
      operationId: getLogos
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logos'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - Logos
      description: Upload a new logo
      operationId: uploadLogo
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Logo'
            encoding:
              image:
                contentType: "image/png, image/jpeg"
                style: form
        required: true
      responses:
        "201":
          description: Logo uploaded
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      x-content-type: multipart/form-data
  /logos/{id}/image:
    get:
      tags:
        - Logos
      description: Dowload Logo Image
      operationId: downloadLogoImage
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            pattern: "^[\\w-]+$"
            type: string
      responses:
        "200":
          description: image data
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /logos/{id}/meta:
    get:
      tags:
        - Logos
      description: get logo metadata
      operationId: getLogoMetaData
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            pattern: "^[\\w-]+$"
            type: string
      responses:
        "200":
          description: the logo metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoMetaData'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /logos/{id}:
    get:
      tags:
        - Logos
      description: Download logo
      operationId: downloadLogo
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            pattern: "^[\\w-]+$"
            type: string
        - name: Accept
          in: header
          required: false
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: the logo with metadata
          content:
            multipart/form-data:
              schema:
                $ref: '#/components/schemas/Logo'
              encoding:
                image:
                  contentType: "image/png, image/jpeg"
                  style: form
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /doc/openapi.yaml:
    get:
      tags:
        - Documentation
      summary: Returns the API documentation in OpenAPI 3 YAML format
      operationId: getOpenApi
      responses:
        "200":
          description: successful operation
          content:
            application/yaml:
              schema:
                type: string
                format: binary
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /employers:
    get:
      tags:
        - Employer
      summary: List all employers
      operationId: findEmployers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employers'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    post:
      tags:
        - Employer
      summary: Create a new employer
      operationId: createEmployer
      requestBody:
        description: Employer data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employer'
        required: true
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: location of the created employer
              style: simple
              explode: false
              schema:
                type: string
                format: uri
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
      x-content-type: application/json
    delete:
      tags:
        - Employer
      summary: Delete the employers with a certain status
      description: "Delete the employers with a certain status. /!\\ If for an employer\
        \ status = provisional, it does not always mean that they have a provisionalNssoNumber"
      operationId: removeEmployers
      parameters:
        - name: status
          in: query
          description: employer status
          required: true
          style: form
          explode: true
          schema:
            type: string
            enum:
              - definitive
              - provisional
              - unknown
      responses:
        "204":
          description: OK
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /employers/{employerId}:
    get:
      tags:
        - Employer
      summary: "Get an employer by an NSSO number, either definitive, provisional\
        \ or number of provisional or local administration"
      operationId: getEmployer
      parameters:
        - name: employerId
          in: path
          description: any type of NSSO Registration number
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/EmployerId'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employer'
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      tags:
        - Employer
      summary: Delete an employer by any type of NSSO registration number
      operationId: deleteEmployer
      parameters:
        - name: employerId
          in: path
          description: any type of NSSO Registration Number
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "204":
          description: OK
        default:
          description: a problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /health:
    get:
      tags:
        - Monitoring
      summary: Check health of this REST API
      description: This resource is only available to supervision users
      externalDocs:
        url: https://www.gcloud.belgium.be/rest/#health
      operationId: healthCheck
      responses:
        "200":
          description: The service is UP or DEGRADED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
              examples:
                response:
                  value:
                    status: UP
        "500":
          description: The service cannot generate a health response.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        "503":
          description: The service is DOWN
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
              examples:
                response:
                  value:
                    status: DOWN
        default:
          $ref: '#/components/responses/ProblemResponse'
components:
  schemas:
    HealthStatus:
      required:
        - status
      type: object
      properties:
        status:
          type: string
          description: "Level indicating the health status of the service: UP (functioning\
            \ as expected), DOWN (suffering unexpected failures), DEGRADED (partly\
            \ unavailable but service can be continued with reduced functionality),\
            \ or a custom status value"
        details:
          type: string
      description: Response message for the API health
      example:
        details: details
        status: status
    EmployerClasses:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/EmployerClassLink'
        total:
          type: integer
          description: the total number of items across all pages
          format: int32
        self:
          type: string
          description: The URI of the current page
          format: uri
      description: A collection of employerClasses
      example:
        total: 0
        self: https://openapi-generator.tech
        items:
          - null
          - null
    EmployerClassLink:
      allOf:
        - $ref: '#/components/schemas/EmployerClass'
        - $ref: '#/components/schemas/EmployerClassLink_allOf'
    EmployerClass:
      required:
        - value
      type: object
      properties:
        value:
          type: string
        description:
          type: string
        self:
          type: string
          format: uri
      description: The employer class as defined here
      example:
        description: description
        self: https://openapi-generator.tech
        value: value
    Problem:
      type: object
      properties:
        type:
          type: string
          description: An absolute URI that identifies the problem type
          format: uri
          default: about:blank
        href:
          type: string
          description: "An absolute URI that, when dereferenced, provides human-readable\
            \ documentation for the problem type (e.g. using HTML)."
          format: uri
        title:
          type: string
          description: A short summary of the problem type. Written in English and
            readable for engineers (usually not suited for non technical stakeholders
            and not localized).
          example: Service Unavailable
        status:
          maximum: 600
          exclusiveMaximum: true
          minimum: 400
          type: integer
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem.
          format: int32
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of
            the problem
        instance:
          type: string
          description: An absolute URI that identifies the specific occurrence of
            the problem. It may or may not yield further information if dereferenced.
          format: uri
      description: A Problem Details object (RFC 7807)
      example:
        type: urn:problem-type:belgif:payloadTooLarge
        href: https://www.belgif.be/specification/rest/api-guide/problems/payloadTooLarge.html
        title: Payload Too Large
        status: 413
        detail: Request message must not be larger than 10 MB
        instance: urn:uuid:123e4567-e89b-12d3-a456-426614174000
        limit: 10485760
    EconomicalActivities:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/EconomicalActivityLink'
        total:
          type: integer
          description: the total number of items across all pages
          format: int32
        self:
          type: string
          description: The URI of the current page
          format: uri
      description: A collection of Economical Activities
      example:
        total: 0
        self: https://openapi-generator.tech
        items:
          - href: https://openapi-generator.tech
            value: value
          - href: https://openapi-generator.tech
            value: value
    EconomicalActivityLink:
      type: object
      properties:
        value:
          pattern: "^[A-Z]$"
          type: string
          description: The identifier/value of the economical activity is set here
        href:
          type: string
          format: uri
      example:
        href: https://openapi-generator.tech
        value: value
    EconomicalActivity:
      pattern: "^[A-Z]$"
      type: string
      description: The identifier/value of the economical activity is set here
    EconomicalActivityDescription:
      required:
        - value
      type: object
      properties:
        value:
          pattern: "^[A-Z]$"
          type: string
          description: The identifier/value of the economical activity is set here
        description:
          $ref: '#/components/schemas/LocalizedString'
        self:
          type: string
          format: uri
      description: The economical activity of the organization is defined here with
        full details
      example:
        description:
          de: de
          fr: fr
          nl: nl
        self: https://openapi-generator.tech
        value: value
    Organizations:
      required:
        - items
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrganizationLink'
        total:
          type: integer
          description: the total number of items across all pages
          format: int32
        page:
          type: integer
          description: "Index of the current page, default 1"
          format: int32
          default: 1
        pageSize:
          type: integer
          description: "Maximum number of items per page, default 5"
          format: int32
          default: 5
        first:
          type: string
          description: The URI of the first page
          format: uri
        last:
          type: string
          description: The URI of the last page
          format: uri
        next:
          type: string
          description: The URI of the next page
          format: uri
        prev:
          type: string
          description: The URI of the previous page
          format: uri
        self:
          type: string
          description: The URI of the current page
          format: uri
      description: A paged collection of organization links
      example:
        next: https://openapi-generator.tech
        total: 0
        last: https://openapi-generator.tech
        prev: https://openapi-generator.tech
        pageSize: 1
        self: https://openapi-generator.tech
        page: 6
        items:
          - enterpriseNumber: enterpriseNumber
            href: https://openapi-generator.tech
            title: title
          - enterpriseNumber: enterpriseNumber
            href: https://openapi-generator.tech
            title: title
        first: https://openapi-generator.tech
    OrganizationLink:
      type: object
      properties:
        href:
          type: string
          format: uri
        title:
          type: string
        enterpriseNumber:
          pattern: "^[0|1]\\d{9}$"
          type: string
          description: Identifier issued by CBE for a registered organization
      example:
        enterpriseNumber: enterpriseNumber
        href: https://openapi-generator.tech
        title: title
    Organization:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        state:
          $ref: '#/components/schemas/OrganizationState'
        enterpriseNumber:
          pattern: "^[0|1]\\d{9}$"
          type: string
          description: Identifier issued by CBE for a registered organization
        startDate:
          type: string
          format: date
        address:
          $ref: '#/components/schemas/Address'
        lastModificationDate:
          type: string
          format: date-time
      description: "Represents a collection of people organized together into a community\
        \ or other social, commercial or political structure. The group has some common\
        \ purpose or reason for existence which goes beyond the set of people belonging\
        \ to it and can act as an Agent. Organizations are often decomposable into\
        \ hierarchical structures."
      example:
        lastModificationDate: 2000-01-23T04:56:07.000+00:00
        address:
          belgianRegionCode: null
          country:
            name: name
            countryNisCode: 231
          street:
            rrnCode: 801
            name: name
          houseNumber: houseNumber
          municipality:
            code: 64246
            name: name
          boxNumber: boxNumber
          postCode: postCode
        enterpriseNumber: enterpriseNumber
        name: name
        state: null
        startDate: 2000-01-23
    OrganizationState:
      type: string
      enum:
        - active
        - inactive
    EnterpriseNumber:
      pattern: "^[0|1]\\d{9}$"
      type: string
      description: Identifier issued by CBE for a registered organization
    MergePatch:
      type: object
      description: JSON Merge Patch (RFC 7386) request body
    Logos:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LogoLink'
        total:
          type: integer
          description: the total number of items across all pages
          format: int32
        self:
          type: string
          description: The URI of the current page
          format: uri
      description: A collection of logos
      example:
        total: 1
        self: https://openapi-generator.tech
        items:
          - metaData:
              fileName: fileName
              width: 6
              mediaType: image/png
              id: id
              height: 0
            href: https://openapi-generator.tech
          - metaData:
              fileName: fileName
              width: 6
              mediaType: image/png
              id: id
              height: 0
            href: https://openapi-generator.tech
    LogoLink:
      type: object
      properties:
        metaData:
          $ref: '#/components/schemas/LogoMetaData'
        href:
          type: string
          description: Any absolute URI that is using http or https protocol
          format: uri
      example:
        metaData:
          fileName: fileName
          width: 6
          mediaType: image/png
          id: id
          height: 0
        href: https://openapi-generator.tech
    LogoMetaData:
      type: object
      properties:
        id:
          type: string
        fileName:
          type: string
        mediaType:
          type: string
          enum:
            - png
            - jpeg
        height:
          type: integer
        width:
          type: integer
      example:
        fileName: fileName
        width: 6
        mediaType: image/png
        id: id
        height: 0
    Logo:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/LogoMetaData'
        image:
          type: string
          format: binary
    Employers:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/EmployerLink'
        total:
          type: integer
          description: the total number of items across all pages
          format: int32
        self:
          type: string
          description: The URI of the current page
          format: uri
      description: A collection of employers
      example:
        total: 6
        self: https://openapi-generator.tech
        items:
          - employerId: 480497095
            enterpriseNumber: enterpriseNumber
            href: https://openapi-generator.tech
            title: title
          - employerId: 480497095
            enterpriseNumber: enterpriseNumber
            href: https://openapi-generator.tech
            title: title
    EmployerLink:
      type: object
      properties:
        href:
          type: string
          description: Any absolute URI that is using http or https protocol
          format: uri
        title:
          type: string
          description: "Its value is a string and is intended for labelling the link\
            \ with a human-readable identifier (as defined by [RFC5988])."
        employerId:
          maximum: 5999999999
          minimum: 197
          type: integer
          description: "Definitive or provisional NSSO number, assigned to each registered\
            \ employer or local or provincial administration."
          format: int64
        enterpriseNumber:
          pattern: "^[0|1]\\d{9}$"
          type: string
          description: Identifier issued by CBE for a registered organization
      example:
        employerId: 480497095
        enterpriseNumber: enterpriseNumber
        href: https://openapi-generator.tech
        title: title
    Employer:
      required:
        - name
        - organization
      type: object
      properties:
        name:
          type: string
        employerId:
          maximum: 5999999999
          minimum: 197
          type: integer
          description: "Definitive or provisional NSSO number, assigned to each registered\
            \ employer or local or provincial administration."
          format: int64
        organization:
          $ref: '#/components/schemas/OrganizationLink'
        economicalActivities:
          type: array
          items:
            $ref: '#/components/schemas/EconomicalActivityLink'
        employerClasses:
          type: array
          items:
            $ref: '#/components/schemas/EmployerClassLink'
        size:
          $ref: '#/components/schemas/EmployerSize'
        self:
          type: string
          format: uri
      example:
        employerId: "164893015"
        name: Esprit
        organization:
          enterpriseNumber: "0433072831"
    EmployerSize:
      type: string
      enum:
        - small
        - medium
        - large
    EmployerId:
      maximum: 5999999999
      minimum: 197
      type: integer
      description: "Definitive or provisional NSSO number, assigned to each registered\
        \ employer or local or provincial administration."
      format: int64
    LocalizedString:
      type: object
      properties:
        nl:
          type: string
        fr:
          type: string
        de:
          type: string
      description: A description specified in multiple languages
      example:
        de: de
        fr: fr
        nl: nl
    Address:
      required:
        - houseNumber
        - municipality
        - postCode
        - street
      type: object
      properties:
        street:
          $ref: '#/components/schemas/Street'
        houseNumber:
          type: string
        boxNumber:
          type: string
        postCode:
          type: string
        municipality:
          $ref: '#/components/schemas/Municipality'
        belgianRegionCode:
          $ref: '#/components/schemas/BelgianRegionCode'
        country:
          $ref: '#/components/schemas/Country'
      description: An address
      example:
        belgianRegionCode: null
        country:
          name: name
          countryNisCode: 231
        street:
          rrnCode: 801
          name: name
        houseNumber: houseNumber
        municipality:
          code: 64246
          name: name
        boxNumber: boxNumber
        postCode: postCode
    Street:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        rrnCode:
          maximum: 9999
          minimum: 1
          type: integer
          description: Street code assigned by National Registry
      example:
        rrnCode: 801
        name: name
    Municipality:
      required:
        - name
      type: object
      properties:
        name:
          type: string
        code:
          maximum: 99999
          minimum: 10000
          type: integer
          description: Numeric code to identify a Belgian municipality
      example:
        code: 64246
        name: name
    Country:
      required:
        - countryNisCode
      type: object
      properties:
        countryNisCode:
          maximum: 999
          minimum: 100
          type: integer
          description: NIS code representing a country as defined by statbel.fgov.be
        name:
          type: string
      example:
        name: name
        countryNisCode: 231
    BelgianRegionCode:
      type: string
      description: Belgian Region represented by an ISO 3166-2:BE code
      enum:
        - BE-BRU
        - BE-WAL
        - BE-VLG
    StreetRrnCode:
      maximum: 9999
      minimum: 1
      type: integer
      description: Street code assigned by National Registry
    MunicipalityCode:
      maximum: 99999
      minimum: 10000
      type: integer
      description: Numeric code to identify a Belgian municipality
    CountryNisCode:
      maximum: 999
      minimum: 100
      type: integer
      description: NIS code representing a country as defined by statbel.fgov.be
    EmployerClassLink_allOf:
      type: object
      properties:
        href:
          type: string
          format: uri
      example: null
  responses:
    ProblemResponse:
      description: a problem
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  parameters:
    LangQueryParameter:
      name: lang
      in: query
      schema:
        type: string
        enum:
          - fr
          - nl
          - de
